import 'src/globals.scss'
import React from 'react'
import { Inter } from 'next/font/google'
import { getAllCountries } from './api/getAllCountries'
import CountriesProvider from './countries-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const countries: Country[] = await getAllCountries()
  return (
    <html lang="en">
      <CountriesProvider countries={countries}>
        <body className={inter.className}>{children}</body>
      </CountriesProvider>
    </html>
  )
}

export default RootLayout
